services:
    swe-caddy:
        image: caddy:2
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - swe-caddy_data:/data
            - swe-caddy_config:/config
        restart: always
        depends_on:
            - swe-app
            - swe-laravel.test
        networks:
            - swe-sail

    swe-laravel.test:
        build:
            context: laravel-api/vendor/laravel/sail/runtimes/8.1
            dockerfile: laravel-api/docker/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            PHP_IDE_CONFIG: 'serverName=laravel-realworld.test'
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - ./laravel-api:/var/www/html
            - ./.env:/var/www/html/.env
        networks:
            - swe-sail
        depends_on:
            - swe-mysql

    swe-mysql:
        image: mysql/mysql-server:8.0
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "1"
        volumes:
            - swe-mysql:/var/lib/mysql
            - ./laravel-api/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
        networks:
            - swe-sail

    swe-app:
        image: node:22.14
        working_dir: /app
        tmpfs:
            - /tmp
        volumes:
            - ./vue3-app:/app
        command: [ "sh", "-c", "npm install && npm run dev" ]
        networks:
            - swe-sail

networks:
    swe-sail:
        name: laravel-realworld-network
        driver: bridge

volumes:
    swe-mysql:
        name: laravel-api-database
        driver: local
    swe-caddy_data:
        driver: local
    swe-caddy_config:
        driver: local
